package com.nowak.demo.mailing;

import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class MailSender {
    private final static String SMTP_AUTH = "mail.smtp.auth";
    private final static String SMTP_TLS = "mail.smtp.starttls.enable";
    private final static String SMTP_HOST =  "mail.smtp.host";
    private final static String SMTP_PORT = "mail.smtp.port";

    private final static String GMAIL_HOST = "smtp.gmail.com";
    private final static String GMAIL_PORT = "587";

    private InputStream inputStream;
    Properties properties;

    public MailSender() {
        inputStream = getClass().getClassLoader().getResourceAsStream("app.properties");
        properties = new Properties();
        try {
            properties.load(inputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public String sendEmail(String receiver, String subject, String msg, String link) {
        String SENDER = properties.getProperty("sender");
        String SENDER_AUTH_PWD = properties.getProperty("pass");
        Properties props = new Properties();

        props.put(SMTP_AUTH, "true");
        props.put(SMTP_TLS, "true");
        props.put(SMTP_HOST, GMAIL_HOST);
        props.put(SMTP_PORT, GMAIL_PORT);

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(SENDER, SENDER_AUTH_PWD);
            }
        });
        try {
            MimeMessage message = new MimeMessage(session);

            message.addRecipient(Message.RecipientType.TO, new InternetAddress(receiver));
            message.setSubject(subject);
            message.setText(checkDefaultMessage(msg, link));
            Transport.send(message);
        } catch (MessagingException e) {
            e.printStackTrace();
            return " Something went wrong!";
        }
        return " E-mail sent!";
    }

    private String checkDefaultMessage(String msg, String link) {
        if (msg.equals("") || msg.equals(" ") || msg.isEmpty()) {
            msg = "Dear,\nI am sending you invoice which was generated for you.\n\nThe right link is below\n"+link+"\n\nThis message was autogenerated.Do not reply to this e-mail.";
            return msg;
        }
        return msg+"\n"+link;
    }
}
