CREATE DATABASE `invoicer`;

CREATE TABLE users(
id BIGSERIAL NOT NULL PRIMARY KEY,
username VARCHAR(128) DEFAULT NULL,
passwd VARCHAR(128) DEFAULT NULL,
email VARCHAR(128) DEFAULT NULL,
date_of_birth timestamp DEFAULT CURRENT_TIMESTAMP
)

